// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaVoto.Api.Data;

#nullable disable

namespace SistemaVoto.Api.Migrations
{
    [DbContext(typeof(SistemaVotoDbContext))]
    partial class SistemaVotoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVoto.Modelos.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<int?>("ListaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PartidoPolitico")
                        .HasColumnType("text");

                    b.Property<string>("Propuestas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListaId");

                    b.HasIndex("EleccionId", "Nombre");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModoUbicacion")
                        .HasColumnType("integer");

                    b.Property<int>("NumEscanos")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("UsaUbicacion")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Elecciones", t =>
                        {
                            t.HasCheckConstraint("CK_Eleccion_EscanosSegunTipo", "(\"Tipo\" = 0 AND \"NumEscanos\" = 0) OR (\"Tipo\" = 1 AND \"NumEscanos\" > 0)");
                        });
                });

            modelBuilder.Entity("SistemaVoto.Modelos.EleccionUbicacion", b =>
                {
                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("EleccionId", "UbicacionId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("EleccionUbicaciones");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.HistorialVotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaParticipacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashTransaccion")
                        .HasColumnType("text");

                    b.Property<int?>("RecintoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecintoId");

                    b.HasIndex("UbicacionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EleccionId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("HistorialVotaciones");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId", "Nombre");

                    b.ToTable("Listas");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.RecintoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId", "Nombre");

                    b.ToTable("Recintos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Tipo", "Nombre");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Voto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVotoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashActual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPrevio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ListaId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecintoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ListaId");

                    b.HasIndex("RecintoId");

                    b.HasIndex("UbicacionId");

                    b.HasIndex("EleccionId", "CandidatoId");

                    b.HasIndex("EleccionId", "FechaVotoUtc");

                    b.HasIndex("EleccionId", "ListaId");

                    b.ToTable("Votos", t =>
                        {
                            t.HasCheckConstraint("CK_Voto_ExactamenteUno", "(\"CandidatoId\" IS NOT NULL AND \"ListaId\" IS NULL) OR (\"CandidatoId\" IS NULL AND \"ListaId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Candidato", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Eleccion", "Eleccion")
                        .WithMany("Candidatos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVoto.Modelos.Lista", "Lista")
                        .WithMany("Candidatos")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eleccion");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.EleccionUbicacion", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Eleccion", "Eleccion")
                        .WithMany("EleccionUbicaciones")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVoto.Modelos.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.HistorialVotacion", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVoto.Modelos.RecintoElectoral", "Recinto")
                        .WithMany()
                        .HasForeignKey("RecintoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaVoto.Modelos.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaVoto.Modelos.Usuario", "Usuario")
                        .WithMany("HistorialVotaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("Recinto");

                    b.Navigation("Ubicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Lista", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Eleccion", "Eleccion")
                        .WithMany("Listas")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.RecintoElectoral", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Ubicacion", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Ubicacion", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Usuario", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Voto", b =>
                {
                    b.HasOne("SistemaVoto.Modelos.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaVoto.Modelos.Eleccion", "Eleccion")
                        .WithMany("Votos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVoto.Modelos.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaVoto.Modelos.RecintoElectoral", "Recinto")
                        .WithMany()
                        .HasForeignKey("RecintoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaVoto.Modelos.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Candidato");

                    b.Navigation("Eleccion");

                    b.Navigation("Lista");

                    b.Navigation("Recinto");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Eleccion", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("EleccionUbicaciones");

                    b.Navigation("Listas");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Lista", b =>
                {
                    b.Navigation("Candidatos");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Ubicacion", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("SistemaVoto.Modelos.Usuario", b =>
                {
                    b.Navigation("HistorialVotaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
